version: "3.5"

services:

  # MDA 0.9.2 _without_ external Xalan processor
  v09:
    image: ukf/testbed:0.9
    hostname: v09

  # MDA 0.9.2 _with_ external Xalan processor
  v09x:
    image: ukf/testbed:0.9-xalan
    hostname: v09x

  # MDA 0.10.0 _without_ external Xalan processor
  v010:
    image: ukf/testbed:0.10
    hostname: v010

  # MDA 0.10.0 _with_ external Xalan processor
  v010x:
    image: ukf/testbed:0.10-xalan
    hostname: v010x

  # Test driver.
  driver:
    image: ukf/testbed-driver:latest
    hostname: driver
    volumes:
    - type: bind
      source: ./tests
      target: /application/tests
